### ISSUE TITLE
Inventory Movements throws ERROR: KeyError: key :stored_at_start not found

### ISSUE THREAD

**Issue by GMGassner** [SupplyChef/SupplyChainOptimization.jl#5]
Hi,
thank you for creating and maintaining this great package.

I have the following error if I run the [Inventory Movements](https://supplychef.github.io/SupplyChainOptimization.jl/dev/inventory%20movements/#Inventory-Movements) example

```julia
ERROR: KeyError: key :stored_at_start not found
Stacktrace:
 [1] getindex(m::Model, name::Symbol)
   @ JuMP C:\Users\ga82toj\.julia\packages\JuMP\ptoff\src\JuMP.jl:740
 [2] macro expansion
   @ C:\Users\ga82toj\.julia\packages\MutableArithmetics\h0wjj\src\rewrite.jl:322 [inlined]
 [3] macro expansion
   @ C:\Users\ga82toj\.julia\packages\JuMP\ptoff\src\macros.jl:1501 [inlined]
 [4] top-level scope
   @ C:\.........\SupplyChainOptimization\Inventory_Movements.jl:33
````

This happens in Julia 1.8.5 and Julia 1.9.0
I tried to resolve it myself but my competence with this package is not enough to have success.
Thank you in advance and best wishes.

**Comment by SupplyChef** [comment]
Hello,

Thank you for reporting this issue. I updated the documentation.

A bit of background: the optimization model used to keep track of inventory levels at the start and at the end of each period. However doing so is redundant and the latest model was changed to only track inventory levels at the end of each period (the inventory at the start being computed when needed). This change broke the example in the documentation.

The good news is that many inventory movement problems can now be modeled directly without manipulating the optimization model's variables. For example the new documentation uses the 'fixed_cost' attribute of the lane (recently added) instead of accessing internal variables. This should make the modeling a bit easier.

Please let me know if this works for you and feel free to open other issues if not. 

Best.

**Comment by SupplyChef** [comment]
Closing now.
